services:
  web-porto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-porto-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
